name: degree
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get: ^4.1.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^0.2.3
  dotted_line: 3.0.0

dev_dependencies:
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Apple
      fonts:
        - asset: assets/font/AppleSDGothicNeoH.ttf
          weight: 500
        - asset: assets/font/AppleSDGothicNeoL.ttf
          weight: 300
        - asset: assets/font/AppleSDGothicNeoM.ttf
          weight: 400


    - family: Gmarket
      fonts:
        - asset: assets/font/GmarketSansTTFLight.ttf
          weight: 300
        - asset: assets/font/GmarketSansTTFMedium.ttf
          weight: 500

  assets:
    - assets/image/
    - assets/image/general #기타
    - assets/image/AI #AI진료
    - assets/image/Record #복용기록



flutter_native_splash:
  image: assets/image/logo_height_blue.png
  fullscreen: true
  color: "#FFFFFF"
  android_gravity: center




